name: "Final Fantasy III Checklist"

externalLinks:
  defaultUrl: https://finalfantasy.fandom.com/wiki/
  rewrites:
    # Renames
    - [ "Reflect Mail", "Mirror Mail" ]
    - [ "Diamond Mail", "Diamond Armor" ]
    - [ "Princess Sara", "Sara_Altney" ]
    # Enemies
    - pattern: Azrael|Berserker|Carbuncle|Dira|Eater|Fury|Killer Bee|Salamander|Lemur|Basilisk|Vulcan|Cockatrice|Duster|Ouroboros|Sea Dragon|Werewolf
      rewrite: $0 (Final Fantasy III)
    # Bosses
    - pattern: Shinobi
      rewrite: $0 (Final Fantasy III)
    # Locations
    - pattern: Falgabard|Gysahl|Sewers|Sunken Cave
      rewrite: $0 (Final Fantasy III)
    # Misc.
    - pattern: Bestiary|MogNet|Nautilus|Takka|Invincible
      rewrite: $0 (Final Fantasy III)
    # Jobs
    - pattern: Onion Knight
      rewrite: $0 (Final Fantasy III)
    # Armor
    - pattern: Leather Cap|Bronze Bracers
      rewrite: Final_Fantasy_III_armor#$0
    # Weapons
    - pattern: Holy Arrow|Longsword
      rewrite: Final_Fantasy_III_weapons#$0
    # Locations
    - pattern: Floating Continent
      rewrite: Final_Fantasy_III_locations#$0
    # Armor
    - pattern: Mirror Mail|Diamond Armor|Diamond Shield|Behemoth Knife
      rewrite: $0#Final_Fantasy_III
    # Items
    - pattern: Magic Key
      rewrite: $0#Final_Fantasy_III
    # Magic
    - pattern: Sleep|Blizzaga
      rewrite: $0 (ability)#Final_Fantasy_III
    # Stats
    - pattern: HP|Vitality
      rewrite: $0 (stat)#Final_Fantasy_III
    # Other
    - [ "jobs?", Final_Fantasy_III_jobs ]
    - [ " ", "_" ]