name: "Final Fantasy III Checklist"

externalLinks:
  defaultUrl: https://finalfantasy.fandom.com/wiki/
  rewrites:
    # Renames
    - [ "Reflect Mail", "Mirror Mail" ]
    - [ "Diamond Mail", "Diamond Armor" ]
    - [ "Princess Sara", "Sara_Altney" ]
    - [ "ninja_boss", "Ninja_(Final_Fantasy_III_boss)" ]
    - [ "MogNet", "Mognet" ]
    - [ "(revive |recovery |status removal )?[Ww]ellspring", "Healing spring (location)#Final Fantasy III" ]
    # Enemies
    - pattern: Abaia|Azrael|Basilisk|Berserker|Bugbear|Carbuncle|Cockatrice|Dira|Duster|Eater|Firefly|Fury|Garm|Gomory|Gorgon|Greater Demon|Griffon|Helldiver|Killer Bee|King Behemoth|Knocker|Lemur|Lizardman|Ouroboros|Red Cap|Rukh|Salamander|Sea Dragon|Vulcan|Werewolf|Xande's Clone|.* Dragon
      rewrite: $0 (Final Fantasy III)
    # Bosses
    - pattern: Amon|General|Guardian|Iron Giant|Kunoichi|Shinobi|Scylla
      rewrite: $0 (Final Fantasy III)
    - [ "[Oo]din", "$0 (Final Fantasy III boss)" ]
    # Locations
    - pattern: \?\?\?|Canaan|Falgabard|Gysahl|Sewers|.* Cave
      rewrite: $0 (Final Fantasy III)
    # Jobs
    - pattern: ^(?:Bard|Black Belt|Black Mage|Devout|Dark Knight|Dragoon|Evoker|Freelancer|Geomancer|Magus|Monk|Ninja|Onion Knight|Knight|Ranger|Red Mage|Sage|Scholar|Summoner|Thief|Viking|Warrior|White Mage)$
      rewrite: $0 (Final Fantasy III)
    # Skills
    - pattern: Sing
      rewrite: $0 (Final Fantasy III)
    # Misc.
    - pattern: "[Bb]estiary|Cid|Invincible|Mognet|Nautilus|Takka"
      rewrite: $0 (Final Fantasy III)
    # Armor
    - pattern: Leather Cap|Bronze Bracers
      rewrite: Final_Fantasy_III_armor#$0
    # Weapons
    - pattern: Holy Arrow|Longsword
      rewrite: Final_Fantasy_III_weapons#$0
    # Locations
    - pattern: Floating Continent
      rewrite: Final_Fantasy_III_locations#$0
    # Armor
    - pattern: Mirror Mail|Diamond Armor|Diamond Shield|Behemoth Knife
      rewrite: $0#Final_Fantasy_III
    # Items
    - pattern: Magic Key|Lamia Scale
      rewrite: $0#Final_Fantasy_III
    # Stats & Skills
    - pattern: Shadowflare|Strength
      rewrite: $0#Final_Fantasy_III
    # Locations
    - pattern: "[Ii]nn"
      rewrite: $0#Final_Fantasy_III
    # Items
    - pattern: Elixir
      rewrite: $0_(item)#Final_Fantasy_III
    # Weapons
    - pattern: Ultima Weapon|Gungnir
      rewrite: $0 (weapon)#Final_Fantasy_III
    # Magic
    - pattern: ^(Blizzaga|Blizzara|Blizzard|Fira|Firaga|Fire|Mini|Sleep|Thundaga|Thundara|Thunder|Toad)
      rewrite: $0 (ability)#Final Fantasy III
    # Stats
    - [ "Agility", "Speed" ]
    - [ "Intellect", "Intelligence" ]
    - pattern: HP|MP|Speed|Vitality|Intelligence|Mind
      rewrite: $0 (stat)#Final_Fantasy_III
    # Other
    - [ "^jobs?$", Final_Fantasy_III_jobs ]
    - [ " ", "_" ]